#!/bin/bash

# hosts
DNSHOST=p5-dns.5700.network
HTTPHOSTS=(p5-http-a.5700.network)

while getopts p:o:n:u:i: args
do
	case $args in
		p)
			port=$OPTARG
			echo "port = " $port
			;;
		o)
			origin=$OPTARG
			echo "origin = " $origin
			;;
		n)
			name=$OPTARG
			echo "name = " $name
			;;
		u)
			username=$OPTARG
			echo "username = " $username
			;;
		i)
			keyfile=$OPTARG
			echo "keyfile = " $keyfile
			;;
		?)
			echo "usage: ./deployCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
			exit 1
			;;
		esac
done

echo "Running replica server... ..."

for host in $HTTPHOSTS
do
	echo "Running host: " $username@$host
	ssh -i $keyfile $username@$host "./httpserver -p $port -o $origin"
done

echo "Running DNS server at $username@$DNSHOST... ..."
ssh -i $keyfile $username@$DNSHOST "./dnsserver -p $port -n $name"

